function(CONFIGURE_DIRECTORY SRC DEST)
    file(GLOB CONFIG_FILES LIST_DIRECTORIES false CONFIGURE_DEPENDS "${SRC}/*.py") 
    foreach(CONFIG_FILE ${CONFIG_FILES})
        message(STATUS "Config file ${CONFIG_FILE}")
        get_filename_component(CONFIG_FILE_NAME ${CONFIG_FILE} NAME)
        configure_file(${CONFIG_FILE} "${DEST}/${CONFIG_FILE_NAME}")
    endforeach(CONFIG_FILE ${CONFIG_FILES})
    file(GLOB SUBDIRS LIST_DIRECTORIES true "${SRC}/*")
    foreach(SUBDIR ${SUBDIRS})
        if(IS_DIRECTORY ${SUBDIR})
            get_filename_component(SUBDIR_NAME ${SUBDIR} NAME)
            set(DEST_DIR "${DEST}/${SUBDIR_NAME}/")
            CONFIGURE_DIRECTORY(${SUBDIR} ${DEST_DIR})
        endif() 
    endforeach(SUBDIR ${SUBDIRS})

endfunction(CONFIGURE_DIRECTORY SRC DEST)

CONFIGURE_DIRECTORY("${CMAKE_SOURCE_DIR}/Config" "${CMAKE_BINARY_DIR}/Config")
#file(GLOB_RECURSE CONFIG_FILES CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/Config/*.py")
#message(STATUS "Dir is ${CMAKE_CURRENT_SOURCE_DIR}")
#foreach(CONFIG_FILE ${CONFIG_FILES})
#    message(STATUS "Config file \"${CONFIG_FILE}\"")
#    get_filename_component(CONFIG_FILE_NAME ${CONFIG_FILE} NAME)
#    configure_file(${CONFIG_FILE} "${CMAKE_BINARY_DIR}/Config/${CONFIG_FILE_NAME}")
#endforeach(CONFIG_FILE ${CONFIG_FILES})
